[api]
groq_api_key = ""

[models]
router = "llama-3.1-8b-instant"
player = "llama-3.3-70b-versatile"

[models.parameters]
router_max_tokens = 500
player_max_tokens = 2000
temperature = 0.8

[app]
theme = "dark"
